package leesche.smartrecycling.base.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import leesche.smartrecycling.base.entity.BarCodeInfo;
import leesche.smartrecycling.base.entity.CommonUserEntity;
import leesche.smartrecycling.base.entity.Containers;
import leesche.smartrecycling.base.entity.DeliveryRecordEntity;
import leesche.smartrecycling.base.entity.MonitorImgEntity;
import leesche.smartrecycling.base.entity.PocEntity;
import leesche.smartrecycling.base.entity.RubbishPostEntity;
import leesche.smartrecycling.base.entity.UploadRunningLogEntity;
import leesche.smartrecycling.base.entity.UserLoginStyleEntity;
import leesche.smartrecycling.base.entity.WriteOffEntity;

import leesche.smartrecycling.base.dao.BarCodeInfoDao;
import leesche.smartrecycling.base.dao.CommonUserEntityDao;
import leesche.smartrecycling.base.dao.ContainersDao;
import leesche.smartrecycling.base.dao.DeliveryRecordEntityDao;
import leesche.smartrecycling.base.dao.MonitorImgEntityDao;
import leesche.smartrecycling.base.dao.PocEntityDao;
import leesche.smartrecycling.base.dao.RubbishPostEntityDao;
import leesche.smartrecycling.base.dao.UploadRunningLogEntityDao;
import leesche.smartrecycling.base.dao.UserLoginStyleEntityDao;
import leesche.smartrecycling.base.dao.WriteOffEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig barCodeInfoDaoConfig;
    private final DaoConfig commonUserEntityDaoConfig;
    private final DaoConfig containersDaoConfig;
    private final DaoConfig deliveryRecordEntityDaoConfig;
    private final DaoConfig monitorImgEntityDaoConfig;
    private final DaoConfig pocEntityDaoConfig;
    private final DaoConfig rubbishPostEntityDaoConfig;
    private final DaoConfig uploadRunningLogEntityDaoConfig;
    private final DaoConfig userLoginStyleEntityDaoConfig;
    private final DaoConfig writeOffEntityDaoConfig;

    private final BarCodeInfoDao barCodeInfoDao;
    private final CommonUserEntityDao commonUserEntityDao;
    private final ContainersDao containersDao;
    private final DeliveryRecordEntityDao deliveryRecordEntityDao;
    private final MonitorImgEntityDao monitorImgEntityDao;
    private final PocEntityDao pocEntityDao;
    private final RubbishPostEntityDao rubbishPostEntityDao;
    private final UploadRunningLogEntityDao uploadRunningLogEntityDao;
    private final UserLoginStyleEntityDao userLoginStyleEntityDao;
    private final WriteOffEntityDao writeOffEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        barCodeInfoDaoConfig = daoConfigMap.get(BarCodeInfoDao.class).clone();
        barCodeInfoDaoConfig.initIdentityScope(type);

        commonUserEntityDaoConfig = daoConfigMap.get(CommonUserEntityDao.class).clone();
        commonUserEntityDaoConfig.initIdentityScope(type);

        containersDaoConfig = daoConfigMap.get(ContainersDao.class).clone();
        containersDaoConfig.initIdentityScope(type);

        deliveryRecordEntityDaoConfig = daoConfigMap.get(DeliveryRecordEntityDao.class).clone();
        deliveryRecordEntityDaoConfig.initIdentityScope(type);

        monitorImgEntityDaoConfig = daoConfigMap.get(MonitorImgEntityDao.class).clone();
        monitorImgEntityDaoConfig.initIdentityScope(type);

        pocEntityDaoConfig = daoConfigMap.get(PocEntityDao.class).clone();
        pocEntityDaoConfig.initIdentityScope(type);

        rubbishPostEntityDaoConfig = daoConfigMap.get(RubbishPostEntityDao.class).clone();
        rubbishPostEntityDaoConfig.initIdentityScope(type);

        uploadRunningLogEntityDaoConfig = daoConfigMap.get(UploadRunningLogEntityDao.class).clone();
        uploadRunningLogEntityDaoConfig.initIdentityScope(type);

        userLoginStyleEntityDaoConfig = daoConfigMap.get(UserLoginStyleEntityDao.class).clone();
        userLoginStyleEntityDaoConfig.initIdentityScope(type);

        writeOffEntityDaoConfig = daoConfigMap.get(WriteOffEntityDao.class).clone();
        writeOffEntityDaoConfig.initIdentityScope(type);

        barCodeInfoDao = new BarCodeInfoDao(barCodeInfoDaoConfig, this);
        commonUserEntityDao = new CommonUserEntityDao(commonUserEntityDaoConfig, this);
        containersDao = new ContainersDao(containersDaoConfig, this);
        deliveryRecordEntityDao = new DeliveryRecordEntityDao(deliveryRecordEntityDaoConfig, this);
        monitorImgEntityDao = new MonitorImgEntityDao(monitorImgEntityDaoConfig, this);
        pocEntityDao = new PocEntityDao(pocEntityDaoConfig, this);
        rubbishPostEntityDao = new RubbishPostEntityDao(rubbishPostEntityDaoConfig, this);
        uploadRunningLogEntityDao = new UploadRunningLogEntityDao(uploadRunningLogEntityDaoConfig, this);
        userLoginStyleEntityDao = new UserLoginStyleEntityDao(userLoginStyleEntityDaoConfig, this);
        writeOffEntityDao = new WriteOffEntityDao(writeOffEntityDaoConfig, this);

        registerDao(BarCodeInfo.class, barCodeInfoDao);
        registerDao(CommonUserEntity.class, commonUserEntityDao);
        registerDao(Containers.class, containersDao);
        registerDao(DeliveryRecordEntity.class, deliveryRecordEntityDao);
        registerDao(MonitorImgEntity.class, monitorImgEntityDao);
        registerDao(PocEntity.class, pocEntityDao);
        registerDao(RubbishPostEntity.class, rubbishPostEntityDao);
        registerDao(UploadRunningLogEntity.class, uploadRunningLogEntityDao);
        registerDao(UserLoginStyleEntity.class, userLoginStyleEntityDao);
        registerDao(WriteOffEntity.class, writeOffEntityDao);
    }
    
    public void clear() {
        barCodeInfoDaoConfig.clearIdentityScope();
        commonUserEntityDaoConfig.clearIdentityScope();
        containersDaoConfig.clearIdentityScope();
        deliveryRecordEntityDaoConfig.clearIdentityScope();
        monitorImgEntityDaoConfig.clearIdentityScope();
        pocEntityDaoConfig.clearIdentityScope();
        rubbishPostEntityDaoConfig.clearIdentityScope();
        uploadRunningLogEntityDaoConfig.clearIdentityScope();
        userLoginStyleEntityDaoConfig.clearIdentityScope();
        writeOffEntityDaoConfig.clearIdentityScope();
    }

    public BarCodeInfoDao getBarCodeInfoDao() {
        return barCodeInfoDao;
    }

    public CommonUserEntityDao getCommonUserEntityDao() {
        return commonUserEntityDao;
    }

    public ContainersDao getContainersDao() {
        return containersDao;
    }

    public DeliveryRecordEntityDao getDeliveryRecordEntityDao() {
        return deliveryRecordEntityDao;
    }

    public MonitorImgEntityDao getMonitorImgEntityDao() {
        return monitorImgEntityDao;
    }

    public PocEntityDao getPocEntityDao() {
        return pocEntityDao;
    }

    public RubbishPostEntityDao getRubbishPostEntityDao() {
        return rubbishPostEntityDao;
    }

    public UploadRunningLogEntityDao getUploadRunningLogEntityDao() {
        return uploadRunningLogEntityDao;
    }

    public UserLoginStyleEntityDao getUserLoginStyleEntityDao() {
        return userLoginStyleEntityDao;
    }

    public WriteOffEntityDao getWriteOffEntityDao() {
        return writeOffEntityDao;
    }

}
